# Generated by Django 4.2.3 on 2023-07-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=32, unique=True)),
                ('model', models.CharField(max_length=32)),
                ('cars_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Kombi', 'Kombi'), ('Hatchback', 'Hatchback'), ('Suv', 'Suv'), ('Coupe', 'Coupe'), ('Van', 'Van')], max_length=32)),
                ('engine', models.CharField(choices=[('Petrol', 'Benzyna'), ('Hybrid', 'Hybryda'), ('Diesel', 'Diesel'), ('Electric', 'Elektryczny')], max_length=16)),
                ('capacity', models.FloatField()),
                ('year', models.CharField(max_length=4)),
                ('number_of_seats', models.IntegerField()),
                ('Consumption', models.CharField(max_length=8)),
                ('power', models.CharField(max_length=4)),
                ('car_mileage', models.CharField(max_length=7)),
                ('transmission', models.CharField(choices=[('Manual', 'Manualna'), ('Automatic', 'Automatyczna')], max_length=32)),
                ('drive', models.CharField(choices=[('RWD', 'Tylni'), ('FWD', 'Przedni'), ('AWD', '4x4')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('driving_license_no', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('period', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.client')),
                ('take_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents_returned', to='Rent.companybranches')),
                ('take_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents_taken', to='Rent.companybranches')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
