# Generated by Django 4.2.3 on 2023-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Suv', 'Suv'), ('Kombi', 'Kombi'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('FWD', 'Przedni'), ('RWD', 'Tylni'), ('AWD', '4x4')], max_length=32),
        ),
    ]
