# Generated by Django 4.2.3 on 2023-07-30 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rent', '0002_alter_car_cars_type_alter_car_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='Consumption',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Van', 'Van'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Suv', 'Suv'), ('Kombi', 'Kombi')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('RWD', 'Tylni'), ('FWD', 'Przedni'), ('AWD', '4x4')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Electric', 'Elektryczny'), ('Petrol', 'Benzyna'), ('Hybrid', 'Hybryda'), ('Diesel', 'Diesel')], max_length=16),
        ),
    ]
